name: code-npm-release

on:
  push:
    paths:
      - 'combined/2/code/**'
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  code-npm-verify:
    uses: ./.github/workflows/code-npm-verify.yml
    with:
      code-path: 'combined/2/code'

  generate-version:
    needs: code-npm-verify
    name: Generate Version 
    runs-on: ubuntu-latest
    outputs:
      next-release-version: ${{ steps.semantic-release.outputs.next-release-version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'	

      - name: Run semantic versioning
        id: semantic-release       
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}              
        run: |
          npm install -g semantic-release@24.2.0 @semantic-release/changelog@6.0.3 @semantic-release/git@10.0.1 @semantic-release/exec@6.0.3
          npx semantic-release
                  
  build-and-push:
    needs: generate-version
    name: Build and push image to ECR
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.get-image-name.outputs.result }}
      app-name: ${{ steps.get-app-name.outputs.result }}
    env:
      CODE_PATH: 'combined/2/code'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ vars.GH_AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}
    
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get app name
        id: get-app-name
        working-directory: ${{ env.CODE_PATH }}
        run: |
          APP_NAME=$(npm pkg get name | tr -d '"')
          echo "result=$APP_NAME" >> $GITHUB_OUTPUT

      - name: Get image name
        id: get-image-name
        run: |
          echo "result=${{ steps.get-app-name.outputs.result }}:${{ needs.generate-version.outputs.next-release-version }}" >> $GITHUB_OUTPUT

      - name: Build image and push to ECR
        id: build-image-push
        working-directory: ${{ env.CODE_PATH }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: ${{ steps.get-image-name.outputs.result }}
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME .
          docker push $ECR_REGISTRY/$IMAGE_NAME
      
      - name: Update version in package.json
        id: update-version
        working-directory: ${{ env.CODE_PATH }}
        run: |
          npm version ${{ needs.generate-version.outputs.next-release-version }} --no-git-tag-version
          
      - name: Commit changes
        id: commit-changes
        working-directory: ${{ env.CODE_PATH }}
        run: |
          git status
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add package.json
          git commit -m "Update package.json version to ${{ needs.generate-version.outputs.next-release-version }}"
          git push
  
  deploy-to-dev:
    needs: build-and-push
    uses: ./.github/workflows/deploy.yml
    with:
      env: 'dev'
      app-name: ${{ needs.build-and-push.outputs.app-name }}
      image-name: ${{ needs.build-and-push.outputs.image-name }}
  