name: code-npm-node-deploy-snapshots

on:
  pull_request:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment to deploy to'
        required: false
        default: ''
  push:
    paths:
      - 'combined/2/code/**'
    branches:
      - main

jobs:
  identify-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Identify changes
        run: echo "Identifying changes..."

  code-npm-verify:
    uses: ./.github/workflows/code-npm-verify.yml
      
  build-deployable:
    environment:
      name: dev
    needs: [identify-changes, code-npm-verify]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ vars.GH_AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity