name: code-npm-node-deploy-snapshots

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment to deploy to'
        required: false
        default: ''
  push:
    paths:
      - 'combined/2/code/**'
    branches:
      - main

jobs:
  identify-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Identify changes
        run: echo "Identifying changes..."

  code-npm-verify:
    uses: ./.github/workflows/code-npm-verify.yml
      
  build-deployable:
    needs: [identify-changes, code-npm-verify]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and deploy
        run: echo "Building and deploying..."